<DownloadScreenView>
    MDBoxLayout:
        orientation: "vertical"
        MyToolBar:
        MDTabs:
            id: tabs
            Tab:
                icon:"server"
                title:"Download Que"
                MDRaisedButton:
                    text: "Test Button"
            Tab:
                icon:"server"
                title:"Downloaded Files"
                MDRaisedButton:
                    text: "Another Button"