name: Build
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Buildozer action
        # You may pin to the exact commit or the version.
        # uses: ArtemSBulgakov/buildozer-action@5939413afbe1640f71dc6e0d93459210f3d38fca
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
          # Command to start Buildozer. Set to `buildozer ios debug` for iOS
          command: buildozer android debug
          # Path to cloned repository. Set if you specified path for `actions/checkout` action.
          repository_root: .
          # Working directory where buildozer.spec is located. Set to `src` if buildozer.spec is in `src` directory
          #workdir: ../../.
          # Version of Buildozer to install. By default installs latest release
          buildozer_version: stable
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      #- name: Upload artifacts
        #uses: actions/upload-artifact@v2
        #with:
          #name: package
          #path: ${{ steps.buildozer.outputs.filename }}
        
